### ISSUE TITLE
segmentation violation

### ISSUE THREAD

**Issue by jurjendevries** [TheDiscordian/ipfs-sync#11]
I am not fully sure about the version, I don't see a version display option yet. I think it is version 0.1.0 . I was running in tmux and it worked well for a week or so, till the last file update this morning. I got the following output:

2021/02/26 06:33:47 Adding file to /ipfs-sync/sprint/ubuntu-4gb-nbg1-1-ipfs-837fe700.433120-9107246334136144212 ...
2021/02/26 06:33:47 Adding file to /ipfs-sync/sprint/status_running.lock ...
2021/02/26 06:33:47 Adding file to /ipfs-sync/sprint/.git/FETCH_HEAD ...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x6c2b8f]

goroutine 20 [running]:
main.watchDir.func1(0xc00010c190, 0x47, 0x0, 0x0, 0x7b5c20, 0xc0000ff9e0, 0x0, 0x0)
        /home/user/go/src/github.com/TheDiscordian/ipfs-sync/main.go:75 +0x2f
path/filepath.walk(0xc000250a40, 0x38, 0x7bc060, 0xc00005e340, 0xc00027e800, 0x0, 0x7bc060)
        /usr/lib/go/src/path/filepath/path.go:380 +0x213
path/filepath.Walk(0xc000250a40, 0x38, 0xc00027e800, 0xc00005e270, 0x0)
        /usr/lib/go/src/path/filepath/path.go:406 +0x105
main.watchDir.func2(0xc000058140, 0xc000018142, 0x6, 0xc000018120, 0x29, 0xc00027e800, 0xc0003801c0)
        /home/user/go/src/github.com/TheDiscordian/ipfs-sync/main.go:129 +0x9a5
created by main.watchDir
        /home/user/go/src/github.com/TheDiscordian/ipfs-sync/main.go:89 +0x287

**Comment by TheDiscordian** [comment]
Hmm by the looks of it, it tried to sync while `git` was doing an operation, a file or directory likely got removed, and caused it to crash.

It'd be ideal if it didn't full-on crash in this situation. It appears in this instance `FileInfo` became a nil interface. We can check for that. In newer versions it's `fs.DirEntry` but serves the same purpose.

Thanks for the report!
