### ISSUE TITLE
Feature request: Copyright output enhancement

### ISSUE THREAD

**Issue by jurjendevries** [TheDiscordian/ipfs-sync#12]
Currently output of copyright flag
# /ipfs-sync/ipfs-sync-noc -copyright
2021/02/26 09:49:00 Copyright © 2020, The ipfs-sync Contributors. All rights reserved.

Request to change it into:
<date> Copyright © 2020, The ipfs-sync Contributors. All rights reserved. BSD 3-Clause “New” or “Revised” License. https://github.com/TheDiscordian/ipfs-sync/blob/master/LICENSE

**Comment by TheDiscordian** [comment]
Thanks for the suggestion! I suppose it'd be helpful for those who downloaded just the binary and didn't get a copy of the license.

I'll have it changed to:

```
Copyright © 2020, The ipfs-sync Contributors. All rights reserved.
BSD 3-Clause “New” or “Revised” License.
License available at: https://github.com/TheDiscordian/ipfs-sync/blob/master/LICENSE
```
