### ISSUE TITLE
Feature request: Version flag

### ISSUE THREAD

**Issue by jurjendevries** [TheDiscordian/ipfs-sync#13]
Would like to see a version flag option that can print the current installed version e.g.
 /ipfs-sync/ipfs-sync-noc -version
ipfs-sync version 0.2.1

**Comment by TheDiscordian** [comment]
I like this idea. Currently in a pinch you can also get possibly the tag, definitely the commit using `go version -m ./ipfs-sync` if you have `go` installed.
