### ISSUE TITLE
could not resolve name

### ISSUE THREAD

**Issue by Deepak-dash007** [TheDiscordian/ipfs-sync#14]
When I tried to sync a directory. It returned error-
ipfs-sync -dirs "[{\"ID\":\"Example1\",\"Dir\":\"/home/Users/Deepak Dash/Desktop/Test_go1\"}]"

```
cmd name/resolve?arg=k51qzi5uqu5djumqhkhcjt8q5yof4h97usq3ldzb3lg1iw8q3cdbojuo8egagj
{"Message":"could not resolve name","Code":0,"Type":"error"}

panic: runtime error: index out of range [2] with length 1

goroutine 1 [running]:
main.ResolveIPNS(0xc0001920c0, 0x3e, 0xc00011de78, 0x2)
        C:/Users/Deepak Dash/go/src/github.com/TheDiscordian/ipfs-sync/main.go:432 +0x367
main.WatchDog()
        C:/Users/Deepak Dash/go/src/github.com/TheDiscordian/ipfs-sync/main.go:490 +0x80c
main.main()
        C:/Users/Deepak Dash/go/src/github.com/TheDiscordian/ipfs-sync/main.go:634 +0x294
```

When Checked I could see that http.client is nil.
http.client = &{<nil> <nil> <nil> 0

Could you let me know if I have done something wrong ?

**Comment by TheDiscordian** [comment]
Curious, is `dirs` being passed properly? I noticed `"` is used a lot there, how's this work for you? It looks like it's erroring when trying to generate the key.

```bash
ipfs-sync -dirs '[{"ID":"Example1","Dir":"/home/Users/Deepak Dash/Desktop/Test_go1"}]'
```

**Comment by Deepak-dash007** [comment]
My bad. Was pointing to wrong directory. I added the directory path in the config.json and it worked. Thanks!!!
