### ISSUE TITLE
Multiple hashes for same file

### ISSUE THREAD

**Issue by manujchandra** [TheDiscordian/ipfs-sync#15]
I made a directory called website and added 3 files in it - file1, file2 ad file3

I added some text to them.

I used ipfs-sync to add them.

Then I removed file1 and edited file2 to add one more line.

This is the output I am getting after that:

(base) manuj@shelter:~/APPS/ipfs-sync-linux64$ ipfs key list
self
ipfs-sync.mywebsite

(base) manuj@shelter:~/APPS/ipfs-sync-linux64$ ipfs pin ls --type=all
QmbNTPp3wgU4QDxjsJ9v7aNBm3grwkHfno57YjA3Gj8buG indirect
Qme4y8z5nxZd3g4uXPyzUWjthDXoDjTwsPPRseNE6qzETC recursive
QmejyB5JSYNMcJeQbXuPj4W1DM23DxsWrU42JQFqy3Z7Xe indirect
QmQmtJC2QmhpZiX3cp1PTK3AL4xjbF25jDyJ6RPjqXN7AV indirect
QmYCJD2Fp7PMN4xoYeGNz8wDzYtPaB1tuBD8XszmzTg5mq indirect
QmYNc7WdiByB2Li6717UgAcdRXjnMSbDX8FHJLwVWChzcA indirect

(base) manuj@shelter:~/APPS/ipfs-sync-linux64$ ipfs cat QmbNTPp3wgU4QDxjsJ9v7aNBm3grwkHfno57YjA3Gj8buG
This is file 2
This is a second edit

(base) manuj@shelter:~/APPS/ipfs-sync-linux64$ ipfs cat Qme4y8z5nxZd3g4uXPyzUWjthDXoDjTwsPPRseNE6qzETC
Error: this dag node is a directory

(base) manuj@shelter:~/APPS/ipfs-sync-linux64$ ipfs cat QmejyB5JSYNMcJeQbXuPj4W1DM23DxsWrU42JQFqy3Z7Xe
Manuj: No Output - seems like file1 is gone but its hash is still pinned?

(base) manuj@shelter:~/APPS/ipfs-sync-linux64$ ipfs cat QmQmtJC2QmhpZiX3cp1PTK3AL4xjbF25jDyJ6RPjqXN7AV
This is file 2
This is a second edit

(base) manuj@shelter:~/APPS/ipfs-sync-linux64$ ipfs cat QmYCJD2Fp7PMN4xoYeGNz8wDzYtPaB1tuBD8XszmzTg5mq
This is file 3

(base) manuj@shelter:~/APPS/ipfs-sync-linux64$ ipfs cat QmYNc7WdiByB2Li6717UgAcdRXjnMSbDX8FHJLwVWChzcA
This is file 3

Notice that hash QmbNTPp3wgU4QDxjsJ9v7aNBm3grwkHfno57YjA3Gj8buG and QmQmtJC2QmhpZiX3cp1PTK3AL4xjbF25jDyJ6RPjqXN7AV are both showing the contents of file2

and QmYCJD2Fp7PMN4xoYeGNz8wDzYtPaB1tuBD8XszmzTg5mq and QmYNc7WdiByB2Li6717UgAcdRXjnMSbDX8FHJLwVWChzcA are showing the contents of file 3!

Using the latest version available in release.

**Comment by TheDiscordian** [comment]
Hmm I wonder if same file, multiple hashes is related to https://github.com/ipfs/go-ipfs/issues/7916.

As for file 1 being gone, but still pinned, unsure, as `pin update` is run, and it shouldn't be pinned. Deleted files should be unpinned by `update`, and they're also removed from MFS, so no output *should* be normal.

**Comment by TheDiscordian** [comment]
If you continue to update those files in the directory, do you end up with lots and lots of pins, or basically the same quantity (1-2 hashes for each)?

**Comment by TheDiscordian** [comment]
Assuming this is/was an issue, it may have been fixed in v0.3.0.

**Comment by manujchandra** [comment]
Let me check and get back to you.

**Comment by lidel** [comment]
FYSA  "ipfs add" and "ipfs files write" commands return different hashes (details why: https://github.com/ipfs-inactive/support/issues/45#issuecomment-269296211)

I feel you can avoid (https://github.com/ipfs/go-ipfs/issues/7916) by switching AddFile in ipfs-sync to use `ipfs.add --pin=false && ipfs.files.cp`, because that guarantees balanced dag and the same CID as from CLI.  This is what we do in ipfs-webui (https://github.com/ipfs/ipfs-webui/issues/676).

**Comment by TheDiscordian** [comment]
> I feel you can avoid hitting [ipfs/go-ipfs#7916](https://github.com/ipfs/go-ipfs/issues/7916) by switching AddFile in ipfs-sync to use `ipfs.add --pin=false && ipfs.files.cp`, because that guarantees creation of a balanced dag and the same CID as from CLI. This is what we do in ipfs-webui ([ipfs/ipfs-webui#676](https://github.com/ipfs/ipfs-webui/issues/676)).

Thanks! This is actually what I did in v0.3.0: https://github.com/TheDiscordian/ipfs-sync/commit/086b613c7569ce042b00dbfaf2faf7a620bf8f53

**Comment by TheDiscordian** [comment]
Closing this as there's been no update, feel free to comment in here if this is still an issue and I'll open it back up!
