### ISSUE TITLE
bug: JSON config used in linux binary package 0.4.2

### ISSUE THREAD

**Issue by jurjendevries** [TheDiscordian/ipfs-sync#35]
The https://github.com/TheDiscordian/ipfs-sync/releases/download/v0.4.2/ipfs-sync-linux64.tar.xz is using JSON in systemd/README.md and systemd/user/ipfs-sync.service instead of YAML #25 

Ps. I didn't checked other releases

**Comment by TheDiscordian** [comment]
v0.4.2 was released before YAML support was added :)
