### ISSUE TITLE
Syncing randomly ends with "Killed"

### ISSUE THREAD

**Issue by ravenclaw900** [TheDiscordian/ipfs-sync#40]
While trying to sync a fairly large (7GB, 46 file) directory, the process ends in the middle of syncing with a SIGKILL.  Note that this was an own compiled executable created with `GOOS=linux GOARCH=arm64 go build` on a different system.

**Comment by TheDiscordian** [comment]
Did you run out of memory during the sync?

**Comment by ravenclaw900** [comment]
Of course, now that I'm monitoring it, everything's working.  I'll let you know if it fails again.

**Comment by ravenclaw900** [comment]
Well, everything seems to be working now.  Sorry for the trouble.  Have a BAT!
