### ISSUE TITLE
Linux Binary GLIBC_2.32 error with Ubuntu 20.04LTS

### ISSUE THREAD

**Issue by jurjendevries** [TheDiscordian/ipfs-sync#5]
When:
./ipfs-sync 

it returns:

./ipfs-sync: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./ipfs-sync)

I searched for this error and it seems very hard/impossible to have GLIBC_2.32 for Ubuntu 20.04, some users recommends to upgrade to 20.10 to have GLIBC_2.32 support. Since 20.10 is not LTS I don't use it for a server. Possibly we can have Ubuntu 20.04 support for the Linux binary? Thank you.

**Comment by TheDiscordian** [comment]
@jurjendevries does this binary work better? Should be statically linked. [ipfs-sync-noc.zip](https://github.com/TheDiscordian/ipfs-sync/files/5983211/ipfs-sync-noc.zip)

**Comment by jurjendevries** [comment]
@TheDiscordian Hi, yes this seems to be error free. Thank you.
